version: '3.9'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product_service
      - user_service
    networks:
      - default
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - default
  product_service:
    build:
      context: .
      dockerfile: ./product_service/Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./product_service:/product
    networks:
      - default
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    command: >
      sh -c "ls && pwd &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./user_service:/user
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
