version: '3.9'

services:
  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
  product_service:
    build:
      context: ./product
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/usr/src/product


volumes:
  postgres_data:
